spring:
  graphql:
    graphiql:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    outOfOrder: false
server:
    port: 8080